server:
  port: 1045
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /
    session:
      timeout: 3600s
  jetty:
    max-http-post-size: 52428800
    accesslog:
      enabled: true
      date-format: yyyy-MM-dd HH:mm:ss Z
spring:
  thymeleaf:
    mode: HTML
    cache: true
  datasource:
    url: jdbc:mysql://111.231.220.72:3306/gallery?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 7890uiop
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none