server:
  port: 1044
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /
    session:
      timeout: 3600s
spring:
  thymeleaf:
    mode: HTML
    cache: true
  datasource:
    url: jdbc:mysql://111.231.220.72:3306/gallery?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 7890uiop
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    